spring:
  data:
    mongodb:
      uri: /aiactivityfitness
      database: aiactivityfitness
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topic:
    name: activity-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8082